# Site Settings
title: Felix E. Rivera-Mariani, PhD
theme: jekyll-theme-cayman
email: friveramariani@gmail.com
baseurl: "http://friveramariani.github.io" # the subpath of your site, e.g. /blog/
url: "http://www.friveram.com" # the base hostname & protocol for your site
twitter_username: friveramariani  
github_username:  friveramariani
